import type { SiteConfig } from "@/types";

export const DEFAULT_CONFIG: SiteConfig = {
  titulo: "XXVII Fiesta Nacional e Internacional del Caballo",
  subtitulo: "Trancas • Tucumán • Argentina",
  bienvenida: "Usted ha sido cordialmente invitado",
  encabezado: "Invitación oficial · Edición 2026",
  boton_abrir: "Abrir Invitación",
  carta_fuente: "editorial",
  carta_tamano: 18,
  carta_grosor: 600,
  carta: `Es un honor para la Municipalidad de Trancas dirigirse a Ud. con el fin de invitarlo/a cordialmente a la XXVII Fiesta Nacional e Internacional del Caballo, celebración que reúne tradición, cultura y el prestigio de nuestra identidad gaucha.

Durante cuatro jornadas, Trancas —Primer Pueblo Gaucho de la Argentina— abrirá sus puertas a autoridades, embajadores, funcionarios e invitados especiales para compartir actos protocolares, demostraciones ecuestres, expresiones del folclore nacional y el espíritu hospitalario que distingue a nuestra tierra.

Su presencia constituirá un alto honor para nuestro pueblo y fortalecerá el valor institucional de una fiesta que es patrimonio vivo de Tucumán y de la República Argentina.

Aguardamos el privilegio de recibirlo/a.`,
  fecha_evento: "2026-10-08T21:00:00-03:00",
  fecha_fin: "2026-10-11T23:59:00-03:00",
  horarios: "Jueves 8 al domingo 11 de octubre de 2026 · Apertura de puertas desde las 18:00 hs · Actos principales a partir de las 21:00 hs",
  ubicacion: "Club Deportivo Trancas",
  ubicacion_detalle: "Trancas, Provincia de Tucumán, República Argentina",
  mapa_url: "https://www.google.com/maps/search/?api=1&query=Club+Deportivo+Trancas+Tucumán",
  mapa_embed:
    "https://maps.google.com/maps?q=Club%20Deportivo%20Trancas%2C%20Trancas%2C%20Tucum%C3%A1n&t=&z=15&ie=UTF8&iwloc=&output=embed",
  accesos: "Ingreso protocolar por acceso principal · Estacionamiento reservado para autoridades · Acreditación en mesa de recepción",
  info_protocolar:
    "Se solicita puntualidad. Vestimenta: formal o tradicional criolla de gala. Mesa protocolar sujeta a confirmación previa. Ante consultas de ceremonial, contactar a la Municipalidad de Trancas.",
  musica_url: "",
  video_url: "",
  logo_fiesta: "/images/brand/logo-oficial.png",
  logo_municipalidad: "/images/brand/logo-oficial.png",
  logo_tucuman: "/images/brand/logo-oficial.png",
  evento_fondo_url: "/images/gallery-caballo.png",
  evento_overlay: 58,
  evento_fecha_texto: "",
  evento_hora_texto: "",
  evento_lugar_texto: "",
  cronograma_fondo_url: "/images/gallery-gauchos.png",
  cronograma_overlay: 58,
  cronograma_titulo: "",
  firmas: [
    {
      nombre: "Dr. Antonio Moreno",
      cargo: "Intendente Municipal de Trancas",
    },
    {
      nombre: "Roberto Moreno",
      cargo: "Legislador Provincial",
    },
  ],
  cronograma: [
    {
      id: "1",
      dia: "Jueves",
      fecha: "2026-10-08",
      hora: "18:00",
      titulo: "Apertura de puertas y recepción protocolar",
      descripcion: "Acreditación de autoridades e invitados especiales.",
      tipo: "protocolar",
    },
    {
      id: "2",
      dia: "Jueves",
      fecha: "2026-10-08",
      hora: "21:00",
      titulo: "Acto de apertura oficial",
      descripcion: "Palabras institucionales y bendición de la XXVII edición.",
      tipo: "oficial",
    },
    {
      id: "3",
      dia: "Jueves",
      fecha: "2026-10-08",
      hora: "22:00",
      titulo: "Noche de folclore y tradición",
      descripcion: "Espectáculo artístico de apertura con expresiones del norte argentino.",
      tipo: "artistico",
    },
    {
      id: "4",
      dia: "Viernes",
      fecha: "2026-10-09",
      hora: "16:00",
      titulo: "Exposición y destrezas ecuestres",
      descripcion: "Muestra de razas, riendas y habilidades del caballo criollo.",
      tipo: "tradicional",
    },
    {
      id: "5",
      dia: "Viernes",
      fecha: "2026-10-09",
      hora: "21:00",
      titulo: "Segunda noche de festival",
      descripcion: "Programa artístico y actos tradicionales.",
      tipo: "artistico",
    },
    {
      id: "6",
      dia: "Sábado",
      fecha: "2026-10-10",
      hora: "17:00",
      titulo: "Desfile gaucho y jineteadas",
      descripcion: "Cortejo tradicional por las calles de Trancas y competencias.",
      tipo: "tradicional",
    },
    {
      id: "7",
      dia: "Sábado",
      fecha: "2026-10-10",
      hora: "21:30",
      titulo: "Gran noche del festival",
      descripcion: "Artistas principales · (grilla sujeta a confirmación oficial).",
      tipo: "artistico",
    },
    {
      id: "8",
      dia: "Domingo",
      fecha: "2026-10-11",
      hora: "18:00",
      titulo: "Cierre de actividades diurnas",
      descripcion: "Ferias, gastronomía regional y muestras artesanales.",
      tipo: "tradicional",
    },
    {
      id: "9",
      dia: "Domingo",
      fecha: "2026-10-11",
      hora: "21:00",
      titulo: "Acto de clausura",
      descripcion: "Ceremonia de cierre y noche final de la XXVII edición.",
      tipo: "oficial",
    },
  ],
  galeria: [
    {
      id: "g1",
      src: "/images/gallery-caballo.png",
      alt: "Caballo criollo al atardecer",
      categoria: "Caballos",
    },
    {
      id: "g2",
      src: "/images/gallery-gauchos.png",
      alt: "Tradición gaucha en desfile",
      categoria: "Tradición",
    },
  ],
  enlaces: [
    {
      id: "l1",
      slug: "gobernador",
      etiqueta: "Gobernador",
      descripcion: "Enlace protocolar para el Gobernador de Tucumán",
      activo: true,
    },
    {
      id: "l2",
      slug: "ministros",
      etiqueta: "Ministros",
      descripcion: "Enlace para ministros y gabinete",
      activo: true,
    },
    {
      id: "l3",
      slug: "legisladores",
      etiqueta: "Legisladores",
      descripcion: "Enlace para legisladores provinciales y nacionales",
      activo: true,
    },
    {
      id: "l4",
      slug: "intendentes",
      etiqueta: "Intendentes",
      descripcion: "Enlace para intendentes municipales",
      activo: true,
    },
    {
      id: "l5",
      slug: "embajadores",
      etiqueta: "Embajadores",
      descripcion: "Enlace para cuerpo diplomático",
      activo: true,
    },
  ],
};
